server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://8.131.59.205:3306/car_rental_contract_manager?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT&createDatabaseIfNotExist=true&nullCatalogMeansCurrent=true
    username: huang
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    loginType: JSON
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    cache: false
  activiti:
    database-schema-update: true
    db-history-used: true
    history-level: full
    check-process-definitions: true
    async-executor-activate: false
#    process-definition-location-prefix: classpath:/processes/
#    process-definition-location-suffixes:
#      - **.bpmn
#      - **.bpmn20.xml



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.carrentalcontract.entity

mapper:
  mappers: com.example.carrentalcontract.common.DbMapper
  identity: MYSQL

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql



logging:
  level:
    com.example.carrentalcontract: debug
    org.activiti.engine.impl.persistence.entity: trace


project:
  manifest:
    file:
      path: classpath:/default-project.json